[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.*"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.*"

[[constraint]]
  name = "github.com/spiegel-im-spiegel/gocli"
  version = "0.8.*"

[[constraint]]
  name = "github.com/spiegel-im-spiegel/go-myjvn"
  version = "0.2.*"

[[constraint]]
  name = "github.com/spiegel-im-spiegel/logf"
  version = "0.2.*"

[[constraint]]
  name = "github.com/lestrrat-go/file-rotatelogs"
  version = "2.1.*"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.*"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.6.*"

[[constraint]]
  name = "github.com/go-gorp/gorp"
  version = "2.1.*"

[[constraint]]
  name = "github.com/Masterminds/squirrel"
  branch = "v1"

[prune]
  go-tests = true
  unused-packages = true
